### ISSUE TITLE
Mapping the research skills of a modern scientist

### ISSUE THREAD

**Issue by chartgerink** [libscie/now-boarding#1]
There are many research skills that are not necessarily related to the topic of the research. Think about preprints, preregistration, choosing a license, and what not.

What do you consider to be important topics that you wish you were taught earlier? This is a place to discuss freely (be mindful of the [code of conduct](https://github.com/libscie/now-boarding/blob/master/CODE_OF_CONDUCT.md) in order to provide a respectful and inclusive discussion).

# Vote count

Updated as discussion goes along.

**Comment by Protohedgehog** [comment]
Hey Chris, this is excellent, nice work! Note that we're also working on something similar now with the Open Science MOOC. People can contribute to the course outline here: https://opensciencemooc.eu/documents/ and then we'll integrate it into the Resources page, and use it for the basis of course development in time! :)

**Comment by chartgerink** [comment]
Thanks @Protohedgehog! So maybe I should give a bit more context, because I have considered whether it was actually worthwhile to do this given the Open Science MOOC (and I think it is complimentary).

The focus of this resource will not necessarily be towards open, but will have a clear coat of open regardless. The idea is to introduce ideas and concepts as early as possible, to have junior researchers think about them when the stakes for their publications/career are relatively low. Joined with a set of commitments for the various topics (e.g., preprint posting: commit to posting none, commit to trying it out on the next paper, commit to doing it for all) to discuss with supervisors etc. it will help engage more people in their direct environment on these issues too. Subsequently, when people from say the same research group have various agreements with the Principal Investigator (PI) there will be a clear need to harmonize. This encourages further discussion.

Does that make sense and deviate from the MOOC, you think? I do agree that resources should be not spent doubly for the same purpose, so if you have concerns about that, do let me know (all content here will be CC 0 so can be repurposed in the MOOC anyway :-))

**Comment by Protohedgehog** [comment]
Hey @chartgerink, this sounds very good, and complimentary. I don't think there will ever be one solution/platform or whatever due to the breadth of what 'open science' is in the context of research skills. We can certainly link to this as a resource for the MOOC too :)

**Comment by chartgerink** [comment]
Closing this issue and recommend opening new issues if you want a topic addressed! Managing the roadmap of the content via [this Project](https://github.com/libscie/now-boarding/projects/1)
