### ISSUE TITLE
Preregistration

### ISSUE THREAD

**Issue by chartgerink** [libscie/now-boarding#15]
**Currently under review in Pull Request #27. Please continue discussion there.**

Preregistration is a relatively new thing, only occurring since 2011 or so. Here the researcher shares and timestamps their confirmatory hypotheses in order to subsequently be able to show that these preceded the data. Exploratory analyses are still possible.

@amscheel would you be up for reviewing content? 🍉 I would ping you in a pull request to review so no need to keep a lookout. If you have things you'd be really keen on seeing in there already, drop them here and I'll take that into account when drafting 💯

**Comment by amscheel** [comment]
Sure, thanks for the invitation! I'm not sure if I have a good grasp of what this project is about yet but I'm happy to help out and familiarise myself with all this.

**Comment by chartgerink** [comment]
@amscheel 💯 for being open to this to begin with.

The project is about onboarding information for junior researchers. For example, [here](https://github.com/libscie/now-boarding/blob/master/content/preprints.md) is a page that explains a bit about preprints and gets junior researchers to think about how they might want to use that. This will be put into a webpage for people to easily browse and learn about various topics as they please. But that website is very much a work in progress 🥖  (see also #2 if you would like to see how that might be presented)
