### ISSUE TITLE
Open Access

### ISSUE THREAD

**Issue by chartgerink** [libscie/now-boarding#8]
There's a lot to open access. Probably it's best to keep this one general and then connect many subparts? I don't know yet.

# Connected topics

* Green open access = postprints #6 
* Gold open access
* Licensing #7

**Comment by chartgerink** [comment]
Draft levels of commitment:

1. Encourage Open Access in new projects, but do not require it for collaboration.
2. Require Open Access in >=25% of your new projects
3. Require Open Access in >=50% of your new projects
4. Require Open Access in >=75% of your new projects
5. Require Open Access in 100% of your new projects

What OA means in this setting, would be up to the person committing and can be included as an additional, first exercise. My personal preference is gold oa with CC BY or CC 0 license, but I understand not everyone has the luxury to do this so a preprint with one of these licenses would also work. It might be worthwhile to include an exercise where people test their definition of OA to that of BOAI for example?

@rainsworth would  appreciate your comments on my braindump.

**Comment by chartgerink** [comment]
@rainsworth would it be possible for you to draft this before March? I am giving a training on March 9th, and this would be worthwhile to have in there in some first form. If not, no worries and just let me know and I'll draft. 👍

**Comment by rainsworth** [comment]
@chartgerink yes, I've started the draft, will have it to you by next week for comments!

**Comment by chartgerink** [comment]
Cool, thanks for the update!

**Comment by chartgerink** [comment]
Addressed in #44
